"""engine/lib/role_spans.py: role spans computed from verl's response_mask index the exact string the
reward manager decodes (skip_special_tokens=True), and anything else fails closed (REVIEW.md R09)."""
from __future__ import annotations

import pytest

from support import ENGINE, load_module

rs = load_module(ENGINE / "lib" / "role_spans.py")

# id -> text; ids < 10 are special tokens (dropped by skip_special_tokens, like <|im_end|>)
VOCAB = {0: "<|im_end|>", 1: "<|im_start|>", 10: "I will search. ", 11: "<tool_call>q</tool_call>",
         20: "user\n<tool_response>", 21: "Paris is the capital.", 22: "</tool_response>\n", 23: "assistant\n",
         30: "<answer>Paris</answer>"}


class Tok:
    def __init__(self, sep: str = ""):
        self.sep = sep

    def decode(self, ids, skip_special_tokens=False):
        return self.sep.join(VOCAB[i] for i in ids if not (skip_special_tokens and i < 10))


# a two-turn episode as ToolAgentLoop lays it out: mask 1 = generated by the model
IDS = [10, 11, 0, 1, 20, 21, 22, 0, 1, 23, 30, 0]
MASK = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]


def test_spans_split_the_decode_into_what_the_model_wrote_and_what_tools_returned():
    spans = rs.compute(Tok(), IDS, MASK)
    full = Tok().decode(IDS, skip_special_tokens=True)
    assistant, tool = rs.split(full, spans)
    assert assistant == ["I will search. <tool_call>q</tool_call>", "<answer>Paris</answer>"]
    assert tool == ["user\n<tool_response>Paris is the capital.</tool_response>\nassistant\n"]
    assert [s[0] for s in spans] == ["assistant", "tool", "assistant"]


def test_spans_are_compact_integers():
    for role, a, b in rs.compute(Tok(), IDS, MASK):
        assert role in ("assistant", "tool") and isinstance(a, int) and isinstance(b, int)


def test_a_mask_that_does_not_match_the_ids_gives_no_spans():
    assert rs.compute(Tok(), IDS, MASK[:-1]) is None


def test_pieces_that_do_not_reassemble_the_decode_give_no_spans():
    assert rs.compute(Tok(sep=" "), IDS, MASK) is None   # decode(list) != join(decode(pieces))


@pytest.mark.parametrize("spans,msg", [
    (None, "no role spans"),
    ("garbage", "malformed"),
    ([["assistant", 0, 5]], "cover 5 of"),                               # too short
    ([["assistant", 0, 5], ["tool", 6, 10]], "not contiguous"),          # a gap
    ([["assistant", 0, 5], ["tool", 4, 10]], "not contiguous"),          # overlap
    ([["narrator", 0, 10]], "not contiguous"),                           # unknown role
])
def test_split_rejects_spans_that_do_not_describe_the_string(spans, msg):
    with pytest.raises(rs.ProvenanceError, match=msg):
        rs.split("0123456789", spans)


def test_an_empty_response_is_fine():
    assert rs.compute(Tok(), [], []) == []
    assert rs.split("", []) == ([], [])
