#!/usr/bin/env python3
"""Isolated collector for the OfficeQA path-report pilot (handoff Section 3, pilot Section 7 step 2).

This produces the RUNTIME-OWNED capture records that ``path_report_pilot.py`` scores.
Its subtle, safety-critical logic -- issuing episode-scoped **observation IDs**, tracking
which results were actually **delivered** to the actor, and taking the **terminal event**
without letting the legacy ``<FINAL_ANSWER>`` forcing manufacture a second commitment -- is
a PURE, CPU-testable state machine (``EpisodeCapture`` + ``run_episode``). The live actor/
tool I/O is a thin wrapper around the proven primitives in ``scripts/eval_officeqa_agentic.py``.

Capture-record schema emitted (consumed by path_report / path_report_pilot):

    {episode_id, question, question_requirements, terminal_text, termination,
     answer_correct (null until a reviewer labels it),
     observations: [{observation_id, order, tool, args, outcome,
                     delivered_text|null, generated_by_request, delivered_to_request|null}],
     raw_executions: [...full outputs incl. undelivered, for audit...],
     raw_turns: [...every assistant text + calls, so failed exploration is retained...]}

Guarantees enforced here (pilot Sections 2-3):
  * observation IDs are RUNTIME-ISSUED and delivered to the actor as ``[observation obs_N]``;
    the actor can only *reference* them, never mint them;
  * a result executed but never delivered (e.g. the consuming actor request errored) has its
    ``delivered_text`` nulled and ``delivered_to_request`` = null -- it is not evidence;
  * multiple calls in ONE turn are all generated by that request and delivered together at the
    NEXT request, so a compute call cannot "see" a read issued in the same parallel batch
    (this is what makes path_report's impossible-chronology check fire);
  * the terminal report is the LAST assistant event only; tool outputs are never scanned for it;
  * no answer is ever synthesized or repaired at the turn cap.

Modes: ``--self-check`` (scripted actor + stub tools; CPU only) and a GATED ``--live`` that
needs an actor endpoint + staged corpus (separate GPU/budget authorization).
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Callable

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import path_report as pr  # noqa: E402  (for the self-check integration + shared constants)

COLLECTOR_VERSION = "path_report_collect/1"
DEFAULT_MAX_TURNS = 16
OBS_MARKER = "[observation {oid}]"        # runtime framing prepended to every delivered result

ActorTurn = dict          # {"text": str, "tool_calls": [(name, args), ...], "error": str|None}


# ---------------------------------------------------------------------------
# actor prompt (adapted from eval's SYSTEM_PROMPT to the terminal-JSON contract)
# ---------------------------------------------------------------------------
PATH_REPORT_SYSTEM_PROMPT = (
    "You are a meticulous financial-data research agent answering questions about U.S. "
    "Treasury Bulletins. Ground every answer in figures you actually retrieve.\n\n"
    "Tools (each result is tagged on its first line as [observation obs_N] -- an id you must "
    "cite later):\n"
    "- search_documents(query, top_k): find the file/table for a figure.\n"
    "- grep_documents(pattern, file_name, year, regex): pin an exact row label/value.\n"
    "- read_document(file_name, start_line, num_lines): read the table cells + headers.\n"
    "- list_documents(year): list available bulletins.\n"
    "- compute(code): run Python (numpy/pandas) for ALL arithmetic.\n\n"
    "When you are done, STOP calling tools and output EXACTLY ONE JSON object and nothing "
    "else -- your answer plus the supporting path:\n"
    '{"answer": "<final value in the units the question asks>", "path": [\n'
    '  {"id": "<short unique id>", "observation": "<obs_N you actually received>", '
    '"claim": "<what that observation shows: the row/period/units/value or the calculation>"'
    ', "depends_on": ["<earlier id>", ...]}\n'
    "]}\n"
    "Rules for the path: cite ONLY observation ids that were delivered to you; a compute step "
    "must list in depends_on the read/search observations whose figures it used; report the "
    "path that actually supports the answer, not every dead end. If the corpus genuinely "
    'lacks the answer, output {"answer": "DATA NOT AVAILABLE", "path": []}.\n\n'
    "Format example (DUMMY content, ignore its values):\n"
    '{"answer": "42 widgets", "path": [\n'
    '  {"id": "s1", "observation": "obs_2", "claim": "the 2020 widget table row shows 42"}]}'
)

PATH_REPORT_FINAL_NUDGE = (
    "You have reached your final step and must NOT call any more tools. Using ONLY the "
    "observations already delivered above, output your terminal JSON object now: "
    '{"answer": ..., "path": [...]}. If the needed figures were not delivered, output '
    '{"answer": "DATA NOT AVAILABLE", "path": []}.'
)

# ---------------------------------------------------------------------------
# SUBMIT-TOOL contract (the ACTIVE contract for live collection): the actor finishes
# by CALLING a submit_report tool with {answer, path} as arguments -- printing text does
# NOT end the task. Models commit to "call the finish tool" far more reliably than to
# "stop calling tools", and the endgame window (nudge + retrieval lockout) pushes a
# still-exploring actor to synthesize before the budget runs out. The no-synthesis
# guarantee is preserved: only an explicit submit produces a terminal report; a turn cap
# still yields NO report. Everything here is env/param-gated so the legacy no-tool-call
# terminal path (already validated by air/83/84/86) is untouched by default.
# ---------------------------------------------------------------------------
SUBMIT_TOOL = "submit_report"
LOCKED_TOOLS_DEFAULT = ("search_documents", "grep_documents")   # kept for backward-compat / unit tests
# "retrieval" = every tool that pulls from the corpus. The endgame forbids ALL of these (the actor
# should already hold its figures) while keeping compute + submit_report.
RETRIEVAL_TOOLS = ("search_documents", "grep_documents", "read_document", "list_documents")
DEFAULT_NUDGE_WINDOW = 5                                        # nudge + lock retrieval this many turns before the cap
DEFAULT_SUBMIT_ONLY_WINDOW = 5                                  # last N turns: submit_report is the ONLY tool

SUBMIT_TOOL_SCHEMA = {
    "type": "function",
    "function": {
        "name": SUBMIT_TOOL,
        "description": (
            "Finish the task: submit your final answer and the supporting path. This is the "
            "ONLY way to end -- do NOT print the report as text. Cite only observation ids "
            "(obs_N) that were actually delivered to you."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "answer": {"type": "string",
                           "description": "Final value in the units the question asks, or 'DATA NOT AVAILABLE'."},
                "path": {
                    "type": "array",
                    "description": "Supporting steps; [] only when answer is DATA NOT AVAILABLE.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "string", "description": "short unique step id"},
                            "observation": {"type": "string", "description": "an obs_N you actually received"},
                            "claim": {"type": "string", "description": "what that observation shows, or the calculation"},
                            "depends_on": {"type": "array", "items": {"type": "string"},
                                           "description": "earlier step ids whose figures a compute step used"},
                        },
                        "required": ["id", "observation", "claim"],
                    },
                },
            },
            "required": ["answer", "path"],
        },
    },
}

# submit-mode system prompt: identical grounding rules, but FINISH = call submit_report.
PATH_REPORT_SYSTEM_PROMPT_SUBMIT = (
    "You are a meticulous financial-data research agent answering questions about U.S. "
    "Treasury Bulletins. Ground every answer in figures you actually retrieve.\n\n"
    "Tools (each result is tagged on its first line as [observation obs_N] -- an id you must "
    "cite later):\n"
    "- search_documents(query, top_k): find the file/table for a figure.\n"
    "- grep_documents(pattern, file_name, year, regex): pin an exact row label/value.\n"
    "- read_document(file_name, start_line, num_lines): read the table cells + headers.\n"
    "- list_documents(year): list available bulletins.\n"
    "- compute(code): run Python (numpy/pandas) for ALL arithmetic.\n"
    "- submit_report(answer, path): FINISH the task. This is the ONLY way to end.\n\n"
    "How this task runs -- plan your steps around it:\n"
    "- You have up to [[MAX_TURNS]] steps, but you need not use them all: call submit_report as "
    "soon as you are confident in your answer.\n"
    "- Do your searching and reading EARLY. For the final [[RETRIEVAL_LOCK]] steps, search, grep, "
    "read and list are closed and only compute and submit_report remain -- so gather every figure "
    "you need before then, and use the end to calculate and write up your answer.\n"
    "- For the final [[SUBMIT_ONLY]] steps, submit_report is the only tool left.\n"
    "- If you have retrieved figures relevant to the question, commit your BEST supported answer "
    'and cite the observations behind it. Reserve answer="DATA NOT AVAILABLE" for when nothing you '
    "retrieved is relevant -- do not decline merely because you are unsure.\n\n"
    "FINISH by calling submit_report with your answer and the supporting path as its arguments. "
    "Do NOT print the JSON as text -- call the tool. Its arguments:\n"
    '  answer: "<final value in the units the question asks>"\n'
    '  path: a list of {"id","observation":"obs_N you received","claim":"row/period/units/value '
    'or the calculation","depends_on":["earlier id",...]}\n'
    "Rules for the path: cite ONLY observation ids that were delivered to you; a compute step "
    "must list in depends_on the read/search observations whose figures it used; report the path "
    "that actually supports the answer, not every dead end."
)

PATH_REPORT_FINAL_NUDGE_SUBMIT = (
    "This is your final step. Call submit_report NOW with your answer and path, using only the "
    "observations already delivered above. If any of them is relevant to the question, give your "
    'best supported answer; use answer="DATA NOT AVAILABLE" only if none is relevant.'
)

# retrieval-lock window nudge (injected each turn inside the outer window; {n} = turns remaining).
ENDGAME_NUDGE = (
    "You have {n} step(s) left, and search, grep, read and list are now closed -- only compute and "
    "submit_report remain. Work with the figures you have already retrieved: compute if you need "
    "arithmetic, then call submit_report. If any delivered observation is relevant to the question, "
    'give your best supported answer rather than "DATA NOT AVAILABLE".'
)

# nudge shown when the actor stops calling tools without submitting (submit mode only).
SUBMIT_REQUIRED_NUDGE = (
    "To finish you must CALL the submit_report tool with your answer and path -- printing text does "
    "not end the task. Call submit_report now, or continue using tools if you are not done."
)

# delivered in place of a locked retrieval call inside the outer (retrieval-lock) window.
RETRIEVAL_LOCKED_MSG = (
    "search, grep, read and list are disabled for the final steps. Answer from the observations "
    "already delivered; compute is available for arithmetic. Finish by calling submit_report."
)

# innermost endgame: submit_report is the ONLY tool (compute + all retrieval locked).
SUBMIT_ONLY_NUDGE = (
    "You have {n} step(s) left and submit_report is now the ONLY tool available. Submit your best "
    "supported answer NOW from the observations you already retrieved, citing them. Do not answer "
    '"DATA NOT AVAILABLE" if any delivered observation is relevant to the question.'
)
SUBMIT_ONLY_LOCKED_MSG = (
    "Only submit_report is available now. Call submit_report with your best supported answer and "
    "the observations that support it."
)


def classify_outcome(text: str) -> str:
    """Coarse outcome tag for a delivered tool result. Call completion is NOT semantic
    support (pilot Section 3.3); this only records error/empty/ok, never acceptance."""
    if not text or not text.strip():
        return "empty"
    s = text.lstrip()
    if s.startswith("Error:"):
        return "error"
    head = s[:80]
    if s.startswith("No ") and re.search(r"found|match|document", head):
        return "empty"
    return "ok"


# ---------------------------------------------------------------------------
# the pure capture state machine
# ---------------------------------------------------------------------------
@dataclass
class EpisodeCapture:
    episode_id: str
    obs_prefix: str = "obs_"
    _n: int = 0
    _obs: dict = field(default_factory=dict)          # oid -> mutable observation dict
    _pending: dict = field(default_factory=dict)      # oid -> target request index (delivery)
    _raw_exec: list = field(default_factory=list)     # full outputs incl. undelivered (audit)

    def new_observation(self, *, tool: str, args: dict, outcome: str, delivered_text: str,
                        generated_by_request: int) -> str:
        self._n += 1
        oid = f"{self.obs_prefix}{self._n}"
        self._obs[oid] = {
            "observation_id": oid, "order": self._n, "tool": tool,
            "args": dict(args or {}), "outcome": outcome,
            "delivered_text": delivered_text,               # nulled at finalize if undelivered
            "generated_by_request": generated_by_request,
            "delivered_to_request": None,
        }
        self._raw_exec.append({"observation_id": oid, "order": self._n, "tool": tool,
                               "args": dict(args or {}), "outcome": outcome,
                               "full_output": delivered_text})
        return oid

    def pend(self, oid: str, *, target: int) -> None:
        self._pending[oid] = target

    def deliver(self, request_index: int) -> None:
        """Mark every observation whose delivery target == request_index as delivered.
        Call this ONLY after the consuming actor request has successfully generated, so a
        failed actor turn leaves its inputs undelivered."""
        for oid, tgt in list(self._pending.items()):
            if tgt == request_index:
                self._obs[oid]["delivered_to_request"] = request_index
                del self._pending[oid]

    def finalize(self, *, question: str, question_requirements: str, terminal_text: str,
                 termination: str, raw_turns: list, max_turns: int) -> dict:
        n_delivered = 0
        for o in self._obs.values():
            if o["delivered_to_request"] is None:
                o["delivered_text"] = None                  # executed but never delivered != evidence
            else:
                n_delivered += 1
        observations = [self._obs[k] for k in sorted(self._obs, key=lambda k: self._obs[k]["order"])]
        return {
            "episode_id": self.episode_id,
            "question": question,
            "question_requirements": question_requirements,
            "terminal_text": terminal_text,
            "termination": termination,
            "answer_correct": None,                          # a reviewer labels this separately
            "observations": observations,
            "raw_executions": self._raw_exec,
            "raw_turns": raw_turns,
            "n_observations": len(observations),
            "n_delivered": n_delivered,
            "max_turns": max_turns,
            "collector_version": COLLECTOR_VERSION,
        }


def _default_render_calls(calls: list, turn: int) -> list:
    return [{"id": f"c{turn}_{i}", "type": "function", "function": {"name": n, "arguments": a}}
            for i, (n, a) in enumerate(calls)]


def _submit_args(calls: list, submit_tool: str):
    """Return the arguments of the first submit_report call in this turn, or None. A submit
    call ALWAYS terminates (even in legacy mode) -- it is the explicit finish action."""
    for name, args in calls:
        if name == submit_tool:
            return args if args is not None else {}
    return None


def _report_text_from_submit(sa) -> str:
    """Turn submit_report arguments into the terminal report JSON text.

    Tool-calling models/parsers frequently serialize a NESTED argument (here ``path``, a list
    of objects) as a JSON *string* rather than a native array -- and sometimes stringify the
    whole arguments object. Decode those so the stored terminal text is the structured report
    ``{answer, path:[...]}`` the model intended. This is lossless (the string is exactly the
    model's JSON); anything that is not valid JSON is handed through unchanged so parse_report
    still judges it (never fabricated into a list)."""
    obj = sa
    if isinstance(obj, str):
        try:
            obj = json.loads(obj)
        except Exception:  # noqa: BLE001 - not JSON: let parse_report flag it
            return obj
    if isinstance(obj, dict):
        obj = dict(obj)
        p = obj.get("path")
        if isinstance(p, str):
            try:
                obj["path"] = json.loads(p)
            except Exception:  # noqa: BLE001 - leave a non-JSON path as-is -> parse_report flags it
                pass
    return json.dumps(obj, ensure_ascii=False)


def run_episode(actor_fn: Callable[[list, int], ActorTurn], tool_fn: Callable[[str, dict], str],
                question: str, *, question_requirements: str = "", episode_id: str = "ep",
                system_prompt: str = PATH_REPORT_SYSTEM_PROMPT, final_nudge: str = PATH_REPORT_FINAL_NUDGE,
                max_turns: int = DEFAULT_MAX_TURNS, reasoning_of: Callable[[str], str] = lambda t: t,
                obs_prefix: str = "obs_",
                require_submit: bool = False, nudge_window: int = 0,
                submit_only_window: int = 0,
                locked_tools: tuple = LOCKED_TOOLS_DEFAULT, submit_tool: str = SUBMIT_TOOL,
                endgame_nudge: str = ENDGAME_NUDGE, submit_required_nudge: str = SUBMIT_REQUIRED_NUDGE,
                retrieval_locked_msg: str = RETRIEVAL_LOCKED_MSG,
                submit_only_nudge: str = SUBMIT_ONLY_NUDGE,
                submit_only_locked_msg: str = SUBMIT_ONLY_LOCKED_MSG) -> dict:
    """Drive one episode and return its capture record. ``actor_fn(messages, request_index)``
    returns ``{"text", "tool_calls":[(name,args)...], "error"}``; ``tool_fn(name, args)``
    returns the tool's delivered text. Both are injected so this is fully unit-testable with
    a scripted actor and stub tools (no model, no network).

    Terminal mechanism:
      * A ``submit_report`` tool call ALWAYS ends the episode; its arguments ARE the report.
      * ``require_submit=False`` (legacy, default): a turn with no tool calls is also terminal
        (the old {answer,path} printed as text). Preserves air/83/84/86 behaviour exactly.
      * ``require_submit=True`` (Replace contract): submit is the ONLY finish -- a no-tool-call
        turn is NOT terminal; it is nudged to submit and the episode continues.
    Two-tier endgame:
      * outer (``nudge_window > 0``): in the last ``nudge_window`` turns a nudge is injected and
        ``locked_tools`` are refused (redirect, outcome 'locked'); compute + submit stay available.
      * inner (``submit_only_window > 0``, meant to be <= nudge_window): in the last
        ``submit_only_window`` turns EVERY tool except ``submit_tool`` is refused -- the actor may
        only submit. A turn cap NEVER synthesizes a report."""
    cap = EpisodeCapture(episode_id, obs_prefix)
    messages = [{"role": "system", "content": system_prompt},
                {"role": "user", "content": question}]
    raw_turns: list = []
    terminal_text = ""
    termination = "incomplete"

    for turn in range(max_turns):
        is_last = (turn == max_turns - 1)
        remaining = max_turns - turn
        in_submit_only = (submit_only_window > 0 and remaining <= submit_only_window)   # inner
        in_window = (nudge_window > 0 and remaining <= nudge_window)                     # outer retrieval-lock
        if is_last:
            messages.append({"role": "user", "content": final_nudge})
        elif in_submit_only:
            messages.append({"role": "user", "content": submit_only_nudge.format(n=remaining)})
        elif in_window:
            messages.append({"role": "user", "content": endgame_nudge.format(n=remaining)})
        try:
            out = actor_fn(messages, turn)
        except Exception as e:  # noqa: BLE001 - an actor fault ends the episode; nothing is delivered
            raw_turns.append({"request_index": turn, "error": f"{type(e).__name__}: {e}"})
            termination = "actor_error"
            break
        if out.get("error"):
            raw_turns.append({"request_index": turn, "text": out.get("text", ""), "error": out["error"]})
            termination = "actor_error"
            break

        # The actor request at `turn` generated successfully -> results targeted at it were
        # actually consumed and are now delivered.
        cap.deliver(turn)

        text = out.get("text", "") or ""
        calls = list(out.get("tool_calls") or [])
        raw_turns.append({"request_index": turn, "text": text,
                          "tool_calls": [{"name": n, "args": a} for n, a in calls]})

        # explicit finish: a submit_report call terminates and carries the report as its args
        # (decoding a path/args the model serialized as a JSON string -- a common tool-call quirk).
        sa = _submit_args(calls, submit_tool)
        if sa is not None:
            terminal_text = _report_text_from_submit(sa)
            termination = "terminal_report"
            break

        if not calls:
            if require_submit:
                # Replace contract: a no-tool-call turn does NOT finish. Nudge to submit, continue.
                if is_last:
                    terminal_text = text
                    termination = "no_submit_at_cap"
                    break
                messages.append({"role": "assistant", "content": reasoning_of(text)})
                messages.append({"role": "user", "content": submit_required_nudge})
                continue
            terminal_text = text
            termination = "terminal_report" if text.strip() else "empty_terminal"
            break
        if is_last:
            # The nudge forbade tools; the model called a non-submit tool anyway. Do NOT
            # dispatch or synthesize.
            terminal_text = text
            termination = "turn_cap_tool_call"
            break

        messages.append({"role": "assistant", "content": reasoning_of(text),
                         "tool_calls": _default_render_calls(calls, turn)})
        for i, (name, args) in enumerate(calls):
            if in_submit_only and name != submit_tool:
                # innermost endgame: only submit_report may run; compute + all retrieval get a
                # redirect tagged 'locked' -- never a real observation of the corpus.
                output, outcome = submit_only_locked_msg, "locked"
            elif in_window and name in locked_tools:
                # retrieval locked in the outer window: respond (template needs one per call) but
                # deliver a redirect, tagged 'locked' -- never a real observation of the corpus.
                output, outcome = retrieval_locked_msg, "locked"
            else:
                try:
                    output = tool_fn(name, args)
                    outcome = classify_outcome(output)
                except Exception as e:  # noqa: BLE001 - a tool fault is a delivered error, not a crash
                    output = f"Error: tool {name} failed: {type(e).__name__}: {e}"
                    outcome = "error"
            oid = cap.new_observation(tool=name, args=args if isinstance(args, dict) else {},
                                      outcome=outcome, delivered_text=output, generated_by_request=turn)
            messages.append({"role": "tool", "name": name, "tool_call_id": f"c{turn}_{i}",
                             "content": OBS_MARKER.format(oid=oid) + "\n" + output})
            cap.pend(oid, target=turn + 1)

    return cap.finalize(question=question, question_requirements=question_requirements,
                        terminal_text=terminal_text, termination=termination,
                        raw_turns=raw_turns, max_turns=max_turns)


def _part_name(eid: str) -> str:
    """Stable, filesystem-safe part filename for an episode id (uid-based -> resume-stable)."""
    return (re.sub(r"[^A-Za-z0-9._-]", "_", str(eid)) or "ep") + ".json"


def _resume_pending(questions: list[dict], parts_dir: str) -> tuple[list[dict], int]:
    """Split questions into (still-to-run, n_already_done) by checking parts_dir for each
    question's durable per-episode file. A question with a uid/episode_id whose part exists is
    skipped (already captured); one without a stable id is always run (its part name would be
    index-derived and non-resumable). Pure + CPU-testable."""
    todo, n_done = [], 0
    existing = set(os.listdir(parts_dir)) if os.path.isdir(parts_dir) else set()
    for q in questions:
        eid = str(q.get("uid") or q.get("episode_id") or "")
        if eid and _part_name(eid) in existing:
            n_done += 1
        else:
            todo.append(q)
    return todo, n_done


def _collect_records(questions: list[dict], episode_runner: Callable[[int, dict], dict],
                     *, concurrency: int = 1,
                     on_result: "Callable[[int, dict], None] | None" = None) -> list[dict]:
    """Run ``episode_runner(index, question) -> record`` for every question and return the
    records in INPUT ORDER. ``concurrency <= 1`` runs them one at a time (the proven
    sequential path). ``concurrency > 1`` runs up to that many episodes at once on a thread
    pool -- each episode is an independent, self-contained ``run_episode`` (its own capture,
    event loop and session) and the work is I/O-bound on the actor endpoint, so threads give
    real overlap. Input order is preserved either way. CPU-testable with a stub runner.

    ``on_result(index, record)`` (optional) is invoked on the calling thread as each episode
    COMPLETES -- used to persist captures incrementally so a kill/timeout keeps finished work."""
    if concurrency <= 1:
        results = []
        for i, q in enumerate(questions):
            rec = episode_runner(i, q)
            if on_result is not None:
                on_result(i, rec)
            results.append(rec)
        return results
    from concurrent.futures import ThreadPoolExecutor, as_completed
    results: list = [None] * len(questions)
    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        futs = {pool.submit(episode_runner, i, q): i for i, q in enumerate(questions)}
        for fut in as_completed(futs):
            idx = futs[fut]
            rec = fut.result()   # episode_runner is exception-safe -> always a record
            results[idx] = rec
            if on_result is not None:
                on_result(idx, rec)
    return results


# ---------------------------------------------------------------------------
# GATED live wrapper -- reuses scripts/eval_officeqa_agentic.py primitives.
# The symbol surface + message rendering are INSPECTION-VERIFIED against eval's
# proven _run_one form: identical assistant tool_calls (id c{turn}_{i}, type
# function, arguments-as-DICT -- a JSON string breaks the Qwen3.5 template) and
# {role:tool,name,tool_call_id,content} responses; _assistant_turn returns a
# 3-tuple; _load_parser -> [(name,args_dict)]; TOOL_IMPLS[name](args_dict).
# Only the SERVED MODEL's runtime behaviour (does it emit parseable qwen3_coder
# calls + one terminal JSON object) still pends a 1-2 episode GPU smoke -- that
# is exactly what air/84 exists to answer.
# ---------------------------------------------------------------------------
def collect_live(questions: list[dict], *, out_dir: str, base_url: str, served_model: str,
                 max_turns: int = DEFAULT_MAX_TURNS,
                 require_submit: bool = True, nudge_window: int = DEFAULT_NUDGE_WINDOW,
                 submit_only_window: int = DEFAULT_SUBMIT_ONLY_WINDOW,
                 concurrency: int = 1) -> str:
    """Collect fresh actor-authored path reports against a served actor model.

    Reuses eval's tokenizer/chat-template rendering and qwen3_coder tool-call parsing, and
    eval's five tool impls, so it inherits the proven format handling; only the capture
    bookkeeping and the terminal-JSON contract are new (and are the CPU-tested core above).
    Sequential per episode (pilot Section 7: rollout may be sequential). Requires a running
    actor endpoint AND a staged corpus -- neither is set up by this script.

    Defaults to the SUBMIT contract (``require_submit=True``): the actor is advertised a
    ``submit_report`` tool and finishes by calling it, and search/grep are locked in the last
    ``nudge_window`` turns (the report-yield fix). Pass ``require_submit=False`` to reproduce
    the legacy no-tool-call terminal used by the first collection (air/85)."""
    import asyncio
    # eval reads its config from env at import time; set what the CLI provided first.
    os.environ.setdefault("EVAL_BASE_URL", base_url)
    os.environ.setdefault("EVAL_MODEL", served_model)
    os.environ.setdefault("EVAL_MAX_TURNS", str(max_turns))
    sys.path.insert(0, os.path.dirname(_HERE))                     # scripts/
    import eval_officeqa_agentic as ev                              # noqa: E402  (lazy; needs aiohttp+transformers)

    if ev.aiohttp is None:
        raise SystemExit("aiohttp unavailable: the live actor path needs the serving image.")

    tok = ev._load_tokenizer()
    parse = ev._load_parser(tok)
    ev._oqt._load_chunks()                                          # pre-warm (freezes loop if lazy)
    ev._oqt._get_bm25()

    # submit mode advertises submit_report alongside eval's 5 tools + uses the submit prompts.
    tools = list(ev.TOOLS) + ([SUBMIT_TOOL_SCHEMA] if require_submit else [])
    sys_prompt = PATH_REPORT_SYSTEM_PROMPT_SUBMIT if require_submit else PATH_REPORT_SYSTEM_PROMPT
    fin_nudge = PATH_REPORT_FINAL_NUDGE_SUBMIT if require_submit else PATH_REPORT_FINAL_NUDGE
    # Make the episode structure PROMINENT + accurate: fill the system prompt with the real budget
    # and window sizes so the actor PLANS for them. A model whose tools vanish unannounced drifts
    # out-of-distribution; one told the rules up front stays in its normal agentic regime.
    if require_submit:
        sys_prompt = (sys_prompt.replace("[[MAX_TURNS]]", str(max_turns))
                                .replace("[[RETRIEVAL_LOCK]]", str(nudge_window))
                                .replace("[[SUBMIT_ONLY]]", str(submit_only_window)))
    # outer endgame window forbids ALL retrieval (search/grep/read/list); compute + submit stay.
    lock_tools = RETRIEVAL_TOOLS

    timeout = ev.aiohttp.ClientTimeout(total=ev.REQ_TIMEOUT)

    def episode_runner(idx: int, q: dict) -> dict:
        # Each episode is fully self-contained: its OWN event loop + aiohttp session (a
        # session binds to its creating loop, so concurrent episodes cannot share one).
        # The render (tokenize=False Jinja), qwen3_coder parse and read-only tool impls
        # are safe under concurrent reads, so threads give real actor-endpoint overlap.
        eid = str(q.get("uid") or q.get("episode_id") or f"ep{idx}")
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            session = loop.run_until_complete(_open_session(ev, timeout))
            try:
                def actor_fn(messages, _req, _sess=session, _loop=loop):
                    text, _c, _tr = _loop.run_until_complete(
                        ev._assistant_turn(_sess, ev._render(tok, messages, tools=tools)))
                    return {"text": text, "tool_calls": parse(text), "error": None}

                def tool_fn(name, args):
                    impl = ev.TOOL_IMPLS.get(name)
                    if impl is None:
                        return f"Error: unknown tool {name!r}."
                    return impl(args if isinstance(args, dict) else {})

                rec = run_episode(actor_fn, tool_fn, q["question"],
                                  question_requirements=q.get("question_requirements", ""),
                                  episode_id=eid,
                                  max_turns=max_turns, reasoning_of=ev._split_reasoning,
                                  system_prompt=sys_prompt, final_nudge=fin_nudge,
                                  require_submit=require_submit, nudge_window=nudge_window,
                                  locked_tools=lock_tools, submit_only_window=submit_only_window)
            finally:
                loop.run_until_complete(session.close())
        except Exception as e:  # noqa: BLE001 - one episode's fault must never kill the batch
            print(f"[collect] {eid}: collector_error {type(e).__name__}: {e}", flush=True)
            rec = EpisodeCapture(eid).finalize(
                question=q["question"], question_requirements=q.get("question_requirements", ""),
                terminal_text=f"[collector_error {type(e).__name__}: {e}]",
                termination="collector_error", raw_turns=[], max_turns=max_turns)
        finally:
            loop.close()
        print(f"[collect] {rec['episode_id']}: {rec['termination']} "
              f"obs={rec['n_observations']} delivered={rec['n_delivered']}", flush=True)
        return rec

    # "Write results as they come" DURABLY + RESUMABLY. An 80-turn deep batch can outrun the job
    # wall-clock, and losing every finished episode to a kill (as the air/113 smoke did -- 170 min
    # -> 0 output) is far worse than a slow run. out_dir is an object-storage-backed Volume (FUSE):
    # a single long-open captures.jsonl is only uploaded on close(), so a kill would lose it even
    # after flush(). Instead, each episode is written to its OWN small file under parts/ and CLOSED
    # immediately -- FUSE uploads a file on close, so every finished capture is durable the instant
    # its episode ends. On (re-)start we SKIP any question already in parts/, so a retry / top-up
    # run RESUMES instead of redoing work or dying on an overwrite guard (the air/114 retry hit
    # exactly that guard). captures.jsonl is then consolidated from ALL parts (resumed + new).
    parts_dir = os.path.join(out_dir, "parts")
    os.makedirs(parts_dir, exist_ok=True)

    def _persist(idx: int, rec: dict) -> None:
        fn = _part_name(rec.get("episode_id") or f"ep{idx}")
        with open(os.path.join(parts_dir, fn), "w", encoding="utf-8") as pf:
            pf.write(json.dumps(rec, ensure_ascii=False))   # one object, closed now -> durable on FUSE

    # RESUME: drop questions whose part file already exists (stable uid-based name).
    if _env_bool("OQ_COLLECT_RESUME", True):
        questions, n_done = _resume_pending(questions, parts_dir)
        if n_done:
            print(f"[collect] resume: {n_done} already in parts/, {len(questions)} still to run",
                  flush=True)

    records = _collect_records(questions, episode_runner, concurrency=concurrency,
                               on_result=_persist)

    # Consolidate ALL parts (this run + any resumed) into captures.jsonl.
    import glob as _glob
    all_recs = []
    for fp in sorted(_glob.glob(os.path.join(parts_dir, "*.json"))):
        try:
            all_recs.append(json.load(open(fp, encoding="utf-8")))
        except Exception as e:  # noqa: BLE001 - a corrupt part must not lose the rest
            print(f"[collect] skipping unreadable part {os.path.basename(fp)}: {e}", flush=True)
    path = os.path.join(out_dir, "captures.jsonl")
    with open(path, "w", encoding="utf-8") as f:
        for r in all_recs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    manifest = {"created_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
                "n_episodes": len(all_recs), "n_this_run": len(records),
                "actor": f"{base_url} model={served_model}",
                "max_turns": max_turns, "require_submit": require_submit, "nudge_window": nudge_window,
                "submit_only_window": submit_only_window,
                "retrieval_lock_tools": list(RETRIEVAL_TOOLS) if require_submit else [],
                "concurrency": concurrency,
                "contract": "submit_report" if require_submit else "no_tool_call_terminal",
                "collector_version": COLLECTOR_VERSION,
                "note": "fresh actor-authored reports; scores are produced offline by path_report_pilot.py"}
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    from collections import Counter
    term_hist = dict(Counter(r["termination"] for r in all_recs))
    print(f"[collect] wrote {len(all_recs)} captures ({len(records)} this run) -> {path}", flush=True)
    print(f"[collect] terminations: {term_hist}", flush=True)
    return path


async def _open_session(ev, timeout):
    return ev.aiohttp.ClientSession(timeout=timeout)


# ---------------------------------------------------------------------------
# self-check: a scripted actor + stub tools, entirely on CPU
# ---------------------------------------------------------------------------
def _scripted_actor(script: list) -> Callable[[list, int], ActorTurn]:
    """Return an actor_fn that replays a fixed list of ActorTurns by request index."""
    def actor_fn(_messages, req):
        return script[req] if req < len(script) else {"text": '{"answer":"DATA NOT AVAILABLE","path":[]}',
                                                       "tool_calls": [], "error": None}
    return actor_fn


def _stub_tools(mapping: dict) -> Callable[[str, dict], str]:
    def tool_fn(name, args):
        key = (name, json.dumps(args, sort_keys=True))
        return mapping.get(key, mapping.get(name, f"No results for {name}."))
    return tool_fn


def _self_check() -> int:
    # A clean 3-turn episode: two reads (turn 0), a compute depending on them (turn 1),
    # then the terminal report (turn 2). This exercises IDs, delivery and chronology.
    script = [
        {"text": "search then read both years",
         "tool_calls": [("read_document", {"file_name": "b1941.txt"}),
                        ("read_document", {"file_name": "b1942.txt"})], "error": None},
        {"text": "now subtract",
         "tool_calls": [("compute", {"code": "print(1.47-1.30)"})], "error": None},
        {"text": ('{"answer":"0.17 trillion dollars","path":['
                  '{"id":"a","observation":"obs_1","claim":"1941 total 1.47 trillion"},'
                  '{"id":"b","observation":"obs_2","claim":"1942 total 1.30 trillion"},'
                  '{"id":"c","observation":"obs_3","depends_on":["a","b"],'
                  '"claim":"compute 1.47-1.30 = 0.17"}]}'),
         "tool_calls": [], "error": None},
    ]
    tools = _stub_tools({
        ("read_document", json.dumps({"file_name": "b1941.txt"}, sort_keys=True)): "1941 grand total: 1.47 trillion",
        ("read_document", json.dumps({"file_name": "b1942.txt"}, sort_keys=True)): "1942 grand total: 1.30 trillion",
        ("compute", json.dumps({"code": "print(1.47-1.30)"}, sort_keys=True)): "0.17",
    })
    rec = run_episode(_scripted_actor(script), tools, "How much did the total decrease?",
                      episode_id="selfcheck", max_turns=8)

    # 1) capture shape
    obs = {o["observation_id"]: o for o in rec["observations"]}
    ok = True
    checks = [
        ("3 observations issued in order", [o["observation_id"] for o in rec["observations"]] == ["obs_1", "obs_2", "obs_3"]),
        ("reads generated at turn 0", obs["obs_1"]["generated_by_request"] == 0 and obs["obs_2"]["generated_by_request"] == 0),
        ("reads delivered at turn 1", obs["obs_1"]["delivered_to_request"] == 1 and obs["obs_2"]["delivered_to_request"] == 1),
        ("compute generated at turn 1, delivered at turn 2", obs["obs_3"]["generated_by_request"] == 1 and obs["obs_3"]["delivered_to_request"] == 2),
        ("delivered_text is exact tool output", obs["obs_1"]["delivered_text"] == "1941 grand total: 1.47 trillion"),
        ("terminal captured, no FINAL_ANSWER forcing", rec["termination"] == "terminal_report" and "<FINAL_ANSWER>" not in rec["terminal_text"]),
    ]
    # 2) the record must feed the offline scorer and score SCORED under a stub judge
    ledger = pr.EpisodeLedger.from_record(rec)
    report = pr.parse_report(rec["terminal_text"])
    ref = pr.check_references(report, ledger)
    verdict = pr.parse_support_verdict('{"path_status":"supported","path_score":0.9,"issues":[]}')
    prev = pr.candidate_preview(report=report, ref=ref, verdict=verdict, answer_correct=True)
    checks.append(("valid report parses", report.ok))
    checks.append(("references resolve (good chronology)", ref.valid))
    checks.append(("scores SCORED end-to-end", prev.status == pr.SCORED))

    print("self-check:")
    for name, passed in checks:
        ok = ok and passed
        print(f"  [{'OK ' if passed else 'BAD'}] {name}")
    print(f"\ncapture: termination={rec['termination']} obs={rec['n_observations']} delivered={rec['n_delivered']}")
    if not ok:
        print("\nSELF-CHECK FAILED")
        return 1
    print("\nSELF-CHECK PASSED (CPU-only; no network/model/GPU used)")
    return 0


# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--self-check", action="store_true", help="run the scripted CPU fixture and exit")
    ap.add_argument("--live", action="store_true", help="collect against a served actor (needs GPU + corpus)")
    ap.add_argument("--questions", help="JSONL/CSV of questions for --live (uid, question[, question_requirements])")
    ap.add_argument("--out", help="immutable output directory for --live")
    ap.add_argument("--actor-base-url", default=None, help="OpenAI-compatible /v1 base URL of the served actor")
    ap.add_argument("--served-model", default="eval", help="served actor model name")
    ap.add_argument("--max-turns", type=int, default=DEFAULT_MAX_TURNS)
    ap.add_argument("--limit", type=int, default=0, help="cap number of episodes (0 = all)")
    ap.add_argument("--difficulty", default="", help="filter questions by difficulty column (e.g. easy)")
    ap.add_argument("--no-require-submit", dest="require_submit", action="store_false",
                    help="use the legacy no-tool-call terminal instead of the submit_report tool")
    ap.add_argument("--nudge-window", type=int, default=DEFAULT_NUDGE_WINDOW,
                    help="turns before the cap to start nudging + lock ALL retrieval (0 = off)")
    ap.add_argument("--submit-only-window", type=int, default=DEFAULT_SUBMIT_ONLY_WINDOW,
                    help="last N turns where submit_report is the ONLY tool (0 = off; <= nudge-window)")
    ap.set_defaults(require_submit=True)
    args = ap.parse_args(argv)

    if args.self_check:
        return _self_check()

    # Env-driven live mode for the serve harness (air/84): serve_and_eval.sh exports
    # EVAL_BASE_URL/EVAL_MODEL after /health, then runs this script with NO CLI args.
    if os.environ.get("OQ_COLLECT_LIVE") == "1":
        return _live_from_env()

    if args.live:
        if not args.actor_base_url or not args.questions or not args.out:
            ap.error("--live requires --actor-base-url, --questions and --out")
        print("WARNING: --live reuses eval_officeqa_agentic primitives; the wiring is inspection-\n"
              "verified but the SERVED MODEL's runtime behaviour is not -- run a 1-2 episode GPU smoke\n"
              "(air/84) and inspect the capture record before trusting a full collection. Needs a\n"
              "staged corpus + separate GPU/budget authorization (see handoff Section 6).",
              file=sys.stderr)
        questions = _select_questions(_load_questions(args.questions),
                                      difficulty=args.difficulty, limit=args.limit)
        if not questions:
            ap.error(f"no questions selected (difficulty={args.difficulty!r} limit={args.limit})")
        collect_live(questions, out_dir=args.out, base_url=args.actor_base_url,
                     served_model=args.served_model, max_turns=args.max_turns,
                     require_submit=args.require_submit, nudge_window=args.nudge_window,
                     submit_only_window=args.submit_only_window)
        return 0

    ap.error("provide --self-check, or --live with its required flags")
    return 2


def _load_questions(path: str) -> list[dict]:
    if path.endswith(".jsonl"):
        with open(path, encoding="utf-8") as f:
            return [json.loads(line) for line in f if line.strip()]
    import csv
    with open(path, newline="", encoding="utf-8") as f:
        return [dict(r) for r in csv.DictReader(f)]


def _select_questions(questions: list[dict], *, difficulty: str = "", limit: int = 0) -> list[dict]:
    """Filter by the ``difficulty`` column (case-insensitive) and cap to the first ``limit``.
    Shared by ``--live`` (flags) and the ``OQ_COLLECT_LIVE`` env path so a smoke can take
    1-2 easy questions from the full eval CSV without a bespoke fixture file."""
    out = questions
    if difficulty:
        d = difficulty.strip().lower()
        out = [q for q in out if str(q.get("difficulty", "")).strip().lower() == d]
    if limit and limit > 0:
        out = out[:limit]
    return out


def _live_from_env() -> int:
    """Live collection driven entirely by env vars -- the entry serve_and_eval.sh uses
    (it exports EVAL_BASE_URL/EVAL_MODEL after /health, then runs this script with no CLI
    args when EVAL_SCRIPT=officeqa/path_report_collect.py and OQ_COLLECT_LIVE=1). See air/84."""
    base_url = os.environ.get("EVAL_BASE_URL")
    out_dir = os.environ.get("OQ_COLLECT_OUT")
    q_path = os.environ.get("OQ_COLLECT_QUESTIONS") or os.environ.get("OFFICEQA_EVAL_CSV")
    if not (base_url and out_dir and q_path):
        print("OQ_COLLECT_LIVE=1 requires EVAL_BASE_URL, OQ_COLLECT_OUT and "
              "OQ_COLLECT_QUESTIONS (or OFFICEQA_EVAL_CSV).", file=sys.stderr)
        return 2
    served = os.environ.get("EVAL_MODEL", "eval")
    max_turns = int(os.environ.get("EVAL_MAX_TURNS", str(DEFAULT_MAX_TURNS)))
    difficulty = os.environ.get("OQ_COLLECT_DIFFICULTY", "")
    limit = int(os.environ.get("OQ_COLLECT_LIMIT", "0") or "0")
    require_submit = _env_bool("OQ_REQUIRE_SUBMIT", True)          # submit contract is the active default
    nudge_window = int(os.environ.get("OQ_NUDGE_WINDOW", str(DEFAULT_NUDGE_WINDOW)) or "0")
    submit_only_window = int(os.environ.get("OQ_SUBMIT_ONLY_WINDOW", str(DEFAULT_SUBMIT_ONLY_WINDOW)) or "0")
    concurrency = int(os.environ.get("OQ_COLLECT_CONCURRENCY", "1") or "1")
    questions = _select_questions(_load_questions(q_path), difficulty=difficulty, limit=limit)
    if not questions:
        print(f"no questions selected from {q_path} "
              f"(difficulty={difficulty!r} limit={limit})", file=sys.stderr)
        return 2
    print(f"[collect] env-driven live: {len(questions)} question(s) from {q_path} "
          f"(difficulty={difficulty or 'any'} limit={limit or 'all'}) actor={base_url} "
          f"model={served} turns={max_turns} submit={require_submit} window={nudge_window} "
          f"submit_only={submit_only_window} conc={concurrency} -> {out_dir}",
          flush=True)
    collect_live(questions, out_dir=out_dir, base_url=base_url,
                 served_model=served, max_turns=max_turns,
                 require_submit=require_submit, nudge_window=nudge_window,
                 submit_only_window=submit_only_window, concurrency=concurrency)
    return 0


def _env_bool(name: str, default: bool) -> bool:
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on")


if __name__ == "__main__":
    sys.exit(main())
